```{r setup}
library(tidyverse); library(Hmisc); library(lm.beta); library(knitr)

opts_chunk$set(warning = FALSE,
               messages = FALSE,
               echo = FALSE,
               fig.width=6.5,
               fig.height=4,
               fig.retina=FALSE,
               dpi=600,
               dev.args=list(type="cairo"),
               fig.ext="png",
               fig.path = "figures/")

dat <- read.csv("../fullData.csv", na.strings = "", stringsAsFactors = F) %>%
  filter(complete.cases(.))
```

```{r re-classing}
dat$PofHelp <- c(100, 50, 25, 75)[factor(dat$PofHelp)]
dat$Grades <- c(77.5, 82.5, 87.5, 92.5)[factor(dat$Grades)]
```

```{r distribution-plots}
# C
hist(dat$C, xlim = c(0, 5), freq = F, col = "#CD2C24", main = "Distribution of Conscientiousness",
     xlab = "Conscientiousness (BFI)", xaxt = "n")
lines(density(dat$C), col = "#63A69F", lwd = 4.5, lty = "dotted")
axis(1, seq(0, 5, .5))

# Grades
hist(dat$Grades, xlim = c(60, 100), breaks = seq(60, 100, 5),
     freq = F, col = "#CD2C24", ylim = c(0, .1),
     main = "Distribution of Grades",
     xlab = "Academic Performance (%)",
     xaxt = "n")
lines(density(dat$Grades), col = "#63A69F", lwd = 4.5, lty = "dotted")
axis(1, seq(60, 100, 5))

# Help Seeking
hist(dat$PofHelp, xlim = c(0, 100), breaks = seq(0, 100, 25),
     freq = F, col = "#CD2C24", ylim = c(0, .1),
     main = "Distribution of Help Seeking",
     xlab = "Probability of Seeking Help (%)",
     xaxt = "n")
lines(density(dat$PofHelp), col = "#63A69F", lwd = 4.5, lty = "dotted")
axis(1, seq(0, 100 , 25))

```